name: edupayaudit
channels:
  - defaults
dependencies:
  - python=3.12
  - pandas>=2.0.0
  - openpyxl>=3.1.0
  - numpy>=1.24.0
  - python-dateutil>=2.8.2
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  - jupyter>=1.0.0
  - notebook>=7.0.0
